# optional:
#     export WORKDIR="/$(basename $(pwd))"
##########################################################
# Run:
#   docker-compose run dev-env
version: "3.7"
services:
  fedora-env:
    privileged: true
    build:
      context: .
    image: ghcr.io/ibm-xaas/fedora-env:main
    volumes:
      # For future ssh use in development
      - ~/.ssh:/home/fedora/.ssh:ro
      - .:/fedora-env
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.gitconfig:/home/fedora/.gitconfig:ro
    working_dir: /fedora-env
